[env]
TERM = "xterm-256color"

[font]
normal = { family = "MxPlus IBM VGA 8x16" }
bold = { family = "Cousine Nerd Font Mono" }
italic = { family = "Agave Nerd Font Mono" }
size = 11

[window]
padding.x = 14
padding.y = 14
decorations = "None"
blur=true

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]

[terminal]
shell = {program = "/bin/zsh", args=["-l"]}
